from datetime import datetime
import json
import tempfile
import os

def format_txt_export(summary_text, title, author, original_text=None, include_metadata=True):
    """Format summary as TXT file"""
    content = ""
    
    if include_metadata:
        content += "=" * 60 + "\n"
        content += "BOOK SUMMARY REPORT\n"
        content += "=" * 60 + "\n\n"
        
        content += f"Title:    {title}\n"
        content += f"Author:   {author}\n"
        content += f"Date:     {datetime.now().strftime('%d %B %Y %H:%M')}\n"
        content += "-" * 60 + "\n\n"
    
    content += "SUMMARY\n"
    content += "-" * 60 + "\n\n"
    content += summary_text + "\n\n"
    
    if original_text:
        content += "-" * 60 + "\n\n"
        content += "ORIGINAL TEXT EXCERPT\n"
        content += "-" * 60 + "\n\n"
        # Limit original text to prevent huge files
        if len(original_text) > 5000:
            original_text = original_text[:5000] + "\n\n... [text truncated for export]"
        content += original_text + "\n\n"
    
    if include_metadata:
        content += "=" * 60 + "\n"
        content += "End of Report\n"
        content += "=" * 60 + "\n"
        content += f"Generated by Book Summarizer Pro on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
    
    return content

def format_json_export(summary_text, title, author, original_text=None):
    """Format summary as JSON file"""
    data = {
        "metadata": {
            "title": title,
            "author": author,
            "export_date": datetime.now().isoformat(),
            "export_format": "json",
            "word_count": len(summary_text.split()),
            "char_count": len(summary_text)
        },
        "summary": summary_text
    }
    
    if original_text:
        data["original_text_excerpt"] = original_text[:2000] if len(original_text) > 2000 else original_text
    
    return json.dumps(data, indent=2, ensure_ascii=False)

def create_clipboard_button(summary_text, button_id="copy-btn"):
    """Create HTML button for clipboard copying"""
    # Escape text for JavaScript
    import html
    escaped_text = html.escape(summary_text).replace("'", "\\'").replace('"', '\\"').replace('\n', '\\n')
    
    html_code = f"""
    <button id="{button_id}" class="copy-btn" 
            onclick="copyToClipboard('{escaped_text}', '{button_id}')"
            style="padding: 10px 20px; background: linear-gradient(45deg, #2196F3, #1976D2); 
                   color: white; border: none; border-radius: 5px; cursor: pointer;
                   font-size: 14px; margin: 10px 0; width: 100%;">
        📋 Copy Summary to Clipboard
    </button>
    <script>
    function copyToClipboard(text, buttonId) {{
        // Clean up escaped characters
        text = text.replace(/\\\\n/g, '\\n').replace(/\\\\'/g, "\\'").replace(/\\\\"/g, '\\"');
        
        // Create a temporary textarea
        const textarea = document.createElement('textarea');
        textarea.value = text;
        document.body.appendChild(textarea);
        textarea.select();
        
        try {{
            const successful = document.execCommand('copy');
            if (successful) {{
                // Show success feedback
                const btn = document.getElementById(buttonId);
                if (btn) {{
                    const originalText = btn.innerHTML;
                    btn.innerHTML = '✅ Copied!';
                    btn.style.background = 'linear-gradient(45deg, #28a745, #218838)';
                    
                    // Create toast notification
                    showToast('Summary copied to clipboard!');
                    
                    setTimeout(() => {{
                        btn.innerHTML = originalText;
                        btn.style.background = '';
                    }}, 2000);
                }}
            }}
        }} catch (err) {{
            console.error('Copy failed:', err);
            alert('Failed to copy text: ' + err);
        }}
        
        document.body.removeChild(textarea);
    }}
    
    function showToast(message) {{
        // Remove existing toast
        const existingToast = document.querySelector('.clipboard-toast');
        if (existingToast) {{
            existingToast.remove();
        }}
        
        // Create new toast
        const toast = document.createElement('div');
        toast.className = 'clipboard-toast';
        toast.innerHTML = message;
        toast.style.cssText = `
            position: fixed;
            top: 20px;
            right: 20px;
            background: #28a745;
            color: white;
            padding: 12px 24px;
            border-radius: 5px;
            z-index: 10000;
            animation: toastFade 2s forwards;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
        `;
        
        document.body.appendChild(toast);
        
        // Add CSS for animation
        const style = document.createElement('style');
        style.textContent = `
            @keyframes toastFade {{
                0% {{ opacity: 0; transform: translateY(-10px); }}
                10% {{ opacity: 1; transform: translateY(0); }}
                90% {{ opacity: 1; transform: translateY(0); }}
                100% {{ opacity: 0; transform: translateY(-10px); }}
            }}
        `;
        document.head.appendChild(style);
        
        // Remove toast after animation
        setTimeout(() => {{
            if (toast.parentNode) {{
                toast.parentNode.removeChild(toast);
            }}
            if (style.parentNode) {{
                style.parentNode.removeChild(style);
            }}
        }}, 2000);
    }}
    </script>
    """
    return html_code

def create_temp_file(content, extension=".txt"):
    """Create a temporary file with content"""
    temp_file = tempfile.NamedTemporaryFile(
        mode='w',
        encoding='utf-8',
        suffix=extension,
        delete=False
    )
    temp_file.write(content)
    temp_file.close()
    return temp_file.name

def cleanup_temp_file(file_path):
    """Remove temporary file"""
    try:
        if os.path.exists(file_path):
            os.unlink(file_path)
    except:
        pass