from reportlab.lib.pagesizes import A4, letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_JUSTIFY
from reportlab.lib import colors
import os

def export_summary_pdf(data, file_path, include_original=False):
    """Generate a professionally formatted PDF summary"""
    
    # Create document
    doc = SimpleDocTemplate(
        file_path,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72
    )
    
    # Get styles
    styles = getSampleStyleSheet()
    
    # Create custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=16,
        spaceAfter=30,
        textColor=colors.HexColor('#2E86AB')
    )
    
    section_style = ParagraphStyle(
        'SectionTitle',
        parent=styles['Heading2'],
        fontSize=14,
        spaceBefore=20,
        spaceAfter=12,
        textColor=colors.HexColor('#A23B72')
    )
    
    text_style = ParagraphStyle(
        'BodyText',
        parent=styles['Normal'],
        fontSize=11,
        spaceAfter=12,
        alignment=TA_JUSTIFY,
        leading=14
    )
    
    meta_style = ParagraphStyle(
        'MetaInfo',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.gray
    )
    
    # Build story
    story = []
    
    # Title
    story.append(Paragraph(f"Summary Report", title_style))
    story.append(Spacer(1, 10))
    
    # Metadata
    story.append(Paragraph(f"<b>Book Title:</b> {data.get('title', 'Unknown')}", meta_style))
    story.append(Paragraph(f"<b>Author:</b> {data.get('author', 'Unknown')}", meta_style))
    story.append(Paragraph(f"<b>Generated:</b> {data.get('date', 'N/A')}", meta_style))
    story.append(Spacer(1, 20))
    
    # Summary Section
    story.append(Paragraph("Summary", section_style))
    story.append(Spacer(1, 5))
    
    # Process summary text for better formatting
    summary_text = data.get('summary_text', 'No summary available.')
    summary_paragraphs = summary_text.split('\n\n')
    for para in summary_paragraphs:
        if para.strip():
            story.append(Paragraph(para.replace('\n', '<br/>'), text_style))
            story.append(Spacer(1, 6))
    
    # Original Text Section (if included)
    if include_original:
        story.append(Spacer(1, 15))
        story.append(Paragraph("Original Text Excerpt", section_style))
        story.append(Spacer(1, 5))
        
        original_text = data.get('original_text', '')
        if original_text:
            # Truncate if too long (keep first 2000 chars)
            if len(original_text) > 2000:
                original_text = original_text[:2000] + "... [text truncated]"
            
            original_paragraphs = original_text.split('\n\n')
            for para in original_paragraphs[:3]:  # Limit to 3 paragraphs
                if para.strip():
                    story.append(Paragraph(para.replace('\n', '<br/>'), text_style))
                    story.append(Spacer(1, 6))
    
    # Footer
    story.append(Spacer(1, 30))
    footer_text = f"Generated by Book Summary App • Page <page>"
    story.append(Paragraph(footer_text, meta_style))
    
    # Build PDF
    doc.build(story)
    
    return file_path